# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "releases", :force => true do |t|
    t.string "name"
    t.string "description"
    t.string "image"
    t.date 'date'
    t.boolean 'publish'
    t.integer 'position'
  end

  create_table "tracks", :force => true do |t|
    t.string 'name', 'file'
    t.integer 'release_id', 'position'
  end

  create_table "users", :force => true do |t|
    t.column "name", :string
    t.column "hashed_password", :string
  end

end
